# Spring Admin Server Details
spring:
  boot:
    admin:
      client:
        url: http://localhost:32768

# Server Port No
server:
  port: 32771

# Spring Actuator End Points
management:
  endpoints:
    web:
      exposure:
        include: '*'

# Logging Details
logger:
  name: drools-service-log
  path: D://Java - MS - Dev End - End//00.Log//${logger.name}.log
logging:
  config: classpath:logback.xml

eureka:
  client:
    #register-with-eureka=false - Every Ms Project should kept ready to register with Eureka Server. 
    #Since we can not register Eureke server Project itself with Eureka server , 
    #So we need to make the default value "true" Inherited from the spring cloud project for "eureka.client.register-with-eureka" property as "false" in Eureka server Project.
    register-with-eureka: true
    # fetch-registry=false - Every MS project should be kept ready for discovery/fetching for communincation while registering with Eureka server.
    # Since Eureka Server Project can not kept ready for fetching/discovery ,
    # Hence we need make the default "true" inhreited from the spring cloud project for "eureka.client.fetch-registry" as "false" in Eureka server Project
    fetch-registry: true

    service-url:
      defaultZone: http://localhost:32770/eureka

drools:
  # Group ID of In-Memory Drools Jar
  groupid: com.stc.drools
  # Artifact ID of In-Memory Drools Jar
  artifactid: drools-api
  # Version of In-Memory Drools
  version: 1.0.0

  # Rule Set Details
  ruleset:
    template:
      path: D://Java - MS - Dev End - End//00.Drools-File-Path
      backup:
        path: D://Java - MS - Dev End - End//04.Drools-File-Backup-Path
      name: ruleset.xlsx
  # Drools Identifier for Firing Rules
  identifier: STC
  # Drools Json Schema Path
  json:
    schema:
      path: D://Java - MS - Dev End - End//04.Drools-Json-Schema-Path
      name: request-json-schema.json

messages:
  basename: classpath:messages
  encoding: UTF-8
